In [2]:
import numpy as np

## Creating Arrays


### 1d Array

In [18]:
aar1 = np.array([1,2,3,4,5])
aar1

array([1, 2, 3, 4, 5])

In [19]:
type(aar1)

numpy.ndarray

In [20]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

### 2d Array

In [21]:
b=np.array([
    [1, 2],
    [3, 4]
])
b

array([[1, 2],
       [3, 4]])

### 3D Array


In [22]:
c =np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])

In [23]:
c

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### 3. Important Properties


In [24]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

In [25]:
a.shape

(2, 3)

In [26]:
a.ndim

2

In [27]:
a.size

6

In [28]:
a.dtype

dtype('int64')

### 4. Special Arrays

In [29]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### 5. Indexing and Slicing

In [34]:
a = np.array([10,20,30,40,50])

In [35]:
a[0]

np.int64(10)

In [36]:
a[-1]

np.int64(50)

In [37]:
a[1:4]   

array([20, 30, 40])

In [38]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

a[1,2]

np.int64(6)

In [39]:
a = np.arange(12)

In [40]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [41]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### 8. Broadcasting

In [42]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

a + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [43]:
a = np.array([
    [1,2,3],
    [4,5,6]
])

b = np.array([10,20,30])

a + b

array([[11, 22, 33],
       [14, 25, 36]])